# Generated by Django 4.0.6 on 2022-08-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMantenimiento',
            fields=[
                ('ficha_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ficha', models.CharField(max_length=4, unique=True)),
                ('dispositivo', models.CharField(max_length=10)),
                ('problema', models.CharField(max_length=70)),
                ('fecha', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
